### ISSUE TITLE
How to disable comfort mode only

### ISSUE THREAD

**Issue by DarkShadowNight** [MislavMandaric/home-assistant-vaillant-vsmart#100]
Hello,

I am looking for a way to disable hot water comfort mode when away. It might save some gas usage.
Yes, I can use "away" of "off" mode but this will also disable prediction for heating as well.
That's not wanted because time between leaving work and arriving home is not long enough to heat up my home during winter time, so I still need to start heating before leaving work.

Any idea? Possible?

Thanks

**Comment by MislavMandaric** [comment]
Hey. I'm not sure I understand what is a "hot water comfort mode" option 😅 

But since this integration works with multiple different vendors (Vaillant and MiGo, at the least) it could be something that I know by some different name. Can you please post a screenshot from the official app showing this feature? That way I might recognize what it is and how that can be achieved.
