### ISSUE TITLE
How to get outside temperature and temperature of the boiler, default schedule

### ISSUE THREAD

**Issue by pes001** [MislavMandaric/home-assistant-vaillant-vsmart#168]
Hello, thank you very much for this integration I started using couple of weeks ago.  
Is it possible to get somehow the outside temperature and the temperature of water in the boiler? I was only able to get the target and current indoor temperature. 
Can I disable default schedule set by mobile app? I thought it can be done by the switch switch.default_plan_schedule but it doesn't work. It always get back to "on". Thanks.

**Comment by MislavMandaric** [comment]
Hey @pes001.

Thank you for using the integration ❤️ 

> Is it possible to get somehow the outside temperature and the temperature of water in the boiler? I was only able to get the target and current indoor temperature.

Outdoor temperature is possible, I think there is already an open PR for adding this functionality, which I'll try to wrap up. The reason why this data point doesn't already exist is that, from my understanding, there is no outside temperature sensor on the boiler itself (at least, not on my Vaillant boiler) and this outside temperature value is value which server sets based on the weather data for your location. Which is a data point you already can get in HA through built in [met](https://www.home-assistant.io/integrations/met) integration.

As for water temperature in the boiler, I'd have to check if it exists in the API response.

> Can I disable default schedule set by mobile app? I thought it can be done by the switch switch.default_plan_schedule but it doesn't work. It always get back to "on". Thanks.

As far as I understand the official app, it is not possible to turn a schedule off, unfortunately. So when you disable it, it doesn't do anything on the server. You can switch to some other schedule by turning it on, which will turn off the one that was previously active. But you can't have all of them off (ie. one always have to be on).

Which is why I forked a [schedule card Lovelace UI card](https://github.com/MislavMandaric/lovelace-standalone-schedule-card), to expose the schedule and make it editable from HA. Now that HA 2022.9 introduced built in schedule mechanism, it's kind of disappointing not being able to use it because it interferes with the built in schedule, but this UI card is very nice and works really well, so its not such a big deal.

The card is currently read only and I still plan on adding all the scheduling options to HA (ie. editing schedules, adding new and deleting existing schedules, etc.). It's also the reason why it's not documented, because it was my proof of concept, that I haven't fully finished.

**Comment by pulss** [comment]
Good day,
How do I get the internal and set temperature into a separate entity please?
Thank you Pavel

**Comment by MislavMandaric** [comment]
Hey @pulss. You can use the [Template integration](https://www.home-assistant.io/integrations/template) to do that.

**Comment by MislavMandaric** [comment]
Outside temperature is added in the latest pre-release and will be available to everyone in the next public release.

As for the water temperature, this will be tracked in #269.
