### ISSUE TITLE
Addon loging out every 2 days

### ISSUE THREAD

**Issue by szmidtpiotr** [MislavMandaric/home-assistant-vaillant-vsmart#190]
For last weeke got notyfication form Homeassistant that action is requierd about Vaillant plugin (need reconfiguration). Then credencial window pop-up and ask me to put email and password back. After that all ok.

**Comment by szmidtpiotr** [comment]
![image](https://user-images.githubusercontent.com/91347162/198866968-46ee95c6-404b-4d8f-8f20-3a7eddfd6ebc.png)
![image](https://user-images.githubusercontent.com/91347162/198866973-e83e96ff-e86f-4263-bcf8-3fd077f5ba55.png)

**Comment by MislavMandaric** [comment]
Hey @szmidtpiotr.

Is the integration logging you out often (ie. "every 2 days") or is it happening ever so often?

This happens when the API rejects the calls as unauthenticated. For me, this usually happens when I test the integration and log into the API multiple times to get multiple tokens. I suppose API marks the tokens as stale or something in that case.

The other cause can be that your tokens that get stored in the HA get corrupted for some reason, so when the state refreshes, the API call gets rejected as unauthenticated.

But this is an expected behavior when that happens. The integration issues a reauth flow and you can enter your credentials again to reload it.
