### ISSUE TITLE
Question: how to feed the actual room temperature

### ISSUE THREAD

**Issue by JasperTack** [MislavMandaric/home-assistant-vaillant-vsmart#195]
I am looking for a way to send the actual room temperature to the vaillant thermostat.

I have home automation set up with knx and each lightswitch has a temperature sensor builtin, which i can use to read out the actual temperature of the room. My Vaillant boiler with VRC 700 thermostat are located in a non heated room, so i can't use the temp sensor of the actual VRC thermostat.

I do have these temperature values however, so would like to find a way on sending these values to the thermostat.

**Comment by MislavMandaric** [comment]
I don't think it's possible to use external temperature sensor for the boiler natively. Or at least I didn't see this API.

But even though it's not natively supported, you could achieve the desired behaviors using Home Assistant automations. For example, you could have two schedules for the Vaillant boiler - "Turned on" schedule and "Turned off" schedule. Then you could create an automation which would use your external sensors as triggers and change between the two schedules as desired (eg. "when temperature on thermometer X goes above 22C, change the schedule to 'turned off schedule'; when temperature on thermometer X goes below 21C, change the schedule to 'turned on schedule').

You could achieve the same with preset modes, without separate schedules (ie. changing between "summer" and "winter" presets based on temperature of the external thermometer).

Not ideal, for sure. But since I don't see how to configure the thermostat itself with external temperature sensor, these workarounds should offer similar behavior at least.
