### ISSUE TITLE
device info, entities naming, unique ids ...

### ISSUE THREAD

**Issue by vneno** [MislavMandaric/home-assistant-vaillant-vsmart#234]
I think, that some naming of entities should be refined.
i.e.:
DHW Swtich should be associated to the boiler not to the thermostat.

I am working on this change.

**Comment by MislavMandaric** [comment]
Thanks for the suggestion, but I'd kindly ask not to do any changes in regards to naming at this point.

This is the refactoring I had in mind for some time now, ever since the HA team announced new naming conventions. But to do that, I want to both introduce new entities with new naming and handle the migration of old entities gracefully.

I'll leave this issue to track progress on it.

**Comment by MislavMandaric** [comment]
Hey @vneno.

As of #265, these changes are now on master, and will be released soon (after I test them in my setup as part of the prerelease process).
